version: 0.2

phases:
  install:
    commands:
      - echo Installing dependency...
      - npm install -g next
      - npm install -g typescript
      - npm install
  build:
    commands:
      - echo "running build command"
      - npm run build
artifacts:
  files:
    - .next/**/*
    - locales/**/*
    - static/**/*
    - package.json
    - next.config.js
    - tsconfig.json
    - tsconfig.server.json