name: myapp

services:
  web:
    image: myapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"

  web1:
    image: myapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"